FROM lscr.io/linuxserver/chromium:latest

ENV RUSTUP_HOME=/opt/rust
ENV CARGO_HOME=/opt/rust

RUN curl https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y --no-modify-path

COPY root/ /

COPY app/ /app/

WORKDIR /app

EXPOSE 9222