FROM debian:trixie AS rust

RUN apt-get update && apt-get install -y curl

RUN curl https://sh.rustup.rs -o rustup.sh && sh rustup.sh -y


FROM lscr.io/linuxserver/chromium:latest

COPY --from=rust /root/.cargo /root/.cargo

COPY root/ /

EXPOSE 9222