pub const COMPUTER_QUERIES: [&str; 48] = [
    "mechanical keyboard",
    "gaming mouse",
    "usb c hub",
    "nvme ssd",
    "27 inch monitor",
    "laptop stand",
    "wifi 6 router",
    "webcam 1080p",
    "noise cancelling headset",
    "raspberry pi kit",
    "usb microphone",
    "stream deck",
    "ergonomic mouse",
    "keyboard wrist rest",
    "monitor arm",
    "laptop dock",
    "thunderbolt dock",
    "portable monitor",
    "external ssd",
    "ssd enclosure",
    "usb c cable",
    "displayport cable",
    "hdmi cable 2.1",
    "network switch",
    "ethernet cable cat6",
    "nas enclosure",
    "ups battery backup",
    "gaming chair",
    "desk mat",
    "standing desk",
    "soldering kit",
    "arduino starter kit",
    "thermal paste",
    "cpu cooler",
    "pc case fan",
    "graphics card support bracket",
    "m.2 heatsink",
    "bluetooth adapter",
    "wifi adapter",
    "usb c sd card reader",
    "sd card",
    "keycap set",
    "mechanical keyboard switch",
    "mouse pad",
    "webcam mount",
    "laptop privacy screen",
    "cable management",
    "desk lamp",
];
